name: SGAdvanced
main: net.yeticraft.xxtraineexx.sgadvanced.SGAdvanced
version: 0.4.7
authors: [XxTRAINEExX]

commands:
  sga:
    description: Interact with Survival Games Advanced
    usage: /<command>
  sgadvanced:
    description: Interact with Survival Games Advanced
    usage: /<command>
permissions:
    sga.*:
        description: Gives access to all Survival Games Advanced features
        children:
            sga.command: true
            sga.platforms: true
            sga.chests: true
            sga.debug: true
            sga.reload: true
            sga.toggle: true
            sga.setupmode: true
            sga.createworld: true
            sga.worldwarp: true
            sga.admin: true
            sga.join: true
            sga.leave: true
            sga.spectate: true
    sga.command:
        description: Allows player access to SGA commands
        default: op
    sga.platforms:
        description: Allows player access to PLATFORMS command
        default: op
    sga.chests:
        description: Allows player access to CHESTS command
        default: op
    sga.debug:
        description: Enables SGA debugging
        default: op
    sga.reload:
        description: Reloads config from disk
        default: op
    sga.toggle:
        description: Turns the plugin ON and OFF
        default: op
    sga.setupmode:
        description: Enables setup mode which turns off game-time functionality
        default: op
    sga.createworld:
        description: Creates a new world for Survival Games
        default: op
    sga.worldwarp:
        description: Creates a new world for Survival Games
        default: op
    sga.admin:
        description: Gives access to specific java methods for testing purposes
        default: op
    sga.admin:
        description: Gives access to specific java methods for testing purposes
        default: op
    sga.join:
        description: Allows player to join the survival games
        default: op
    sga.leave:
        description: Allows player to leave the survival games
        default: op
    sga.spectate:
        description: Allows player to spectate a match
        default: op