name: SGAdvanced
main: net.yeticraft.xxtraineexx.sgadvanced.SGAdvanced
version: 0.4
authors: [XxTRAINEExX]

commands:
  sga:
    description: Interact with Survival Games Advanced
    usage: /<command>
  sgadvanced:
    description: Interact with Survival Games Advanced
    usage: /<command>
permissions:
    sga.*:
        description: Gives access to all Survival Games Advanced features
        children:
            sga.command: true
            sga.platforms: true
            sga.chests: true
            sga.debug: true
            sga.reload: true
            sga.toggle: true
            sga.setupmode: true
    sga.command:
        description: Allows player access to SGA commands
        default: op
    sga.platforms:
        description: Allows player access to PLATFORMS command
        default: op
    sga.chests:
        description: Allows player access to CHESTS command
        default: op
    sga.debug:
        description: Enables SGA debugging
        default: op
    sga.reload:
        description: Reloads config from disk
        default: op
    sga.toggle:
        description: Turns the plugin ON and OFF
        default: op
    sga.setupmode:
        description: Enables setup mode which turns off game-time functionality
        default: op